### ISSUE TITLE
Auto Play Music when connected to specific device

### ISSUE THREAD

**Issue by BaReinhard** [MohammadAG/iOS-AutoAirPlay#4]
I am looking through the code and I just can't seem to see where I might be able to program such a feature.

Currently, as my device connects to an AirPlay device while music is playing the music pauses. I am looking to have the music start to play again, if and only if it is connected to speaker with a specific name. Is this a possibility and if so where would I go about adding this. Forgive me for my inexperience with Objective-C. I am far more familiar with other languages.

**Comment by patriot1889** [comment]
@BaReinhard
I take it this is to use with the RPi Audio Receiver?

Maybe look into the Pi sending a DACP command for the music to start playing?
(see unofficial airplay documentation: http://nto.github.io/AirPlay.html#audio-remotecontrol)


EDIT: See https://www.sugrsugr.com/index.php/airplay-prev-next/
